### PR TITLE
Nova 4 support

### PR DESCRIPTION
**Pull request by theimerj**
# Nova 4 support

Hello everyone, here is a PR for Nova 4 support we worked on with [@kreejzak](https://github.com/kreejzak).

#### If you want to help with testing

In your `composer.json`
```json
"require": {
    "dmitrybubyakin/nova-medialibrary-field": "dev-nova-4",
},
"repositories": [
    {
        "type": "git",
        "url": "https://github.com/dystcz/nova-medialibrary-field"
    },
],
```

Then run `composer update`

#### Good stuff
- most of the functionality seems to work fine
- tests are green ✅

#### Still needs to be done
- documentation adjustments
- thorough user testing (please help)
- after @dmitrybubyakin approves the PR, the documentation has to be split to pre Nova 4 and current versions probably, new release has to be drafted and so on

####  Possible enhancements
- styles (tailwind positioning, spacing, etc.)
- utilise more of Nova 4 default functionality to cleanup the codebase

--- 

Thanks for the kickoff commits [@aemaddin](https://github.com/aemaddin)

### CODE REVIEW

**Comment by dmitrybubyakin** [comment]
@theimerj Wow, that's a huge amount of work! I'm not able to test it now, so let me know when this should be merged

**Comment by theimerj** [comment]
> @theimerj Wow, that's a huge amount of work! I'm not able to test it now, so let me know when this should be merged. Thanks for supporting this package!

Hey @dmitrybubyakin, I will let you know when it reaches "mergeable status" haha. Right now, everyone can try it out and if issues arise, we will react to them. 

It seems that I still have to fix nova composer installation for Github actions somehow.

Anyways, I will let you know. :)

**Comment by theimerj** [comment]
Hello @dmitrybubyakin, I fixed the tests, they are now running green here: [https://github.com/dystcz/nova-medialibrary-field/tree/nova-4](https://github.com/dystcz/nova-medialibrary-field/tree/nova-4)

However, I will need your help, because I had to add my Nova licence to repository secrets. 
Here is the commit: [https://github.com/dystcz/nova-medialibrary-field/commit/7867fa6f0ceb93eb2f059d33f96c250cb1188deb](https://github.com/dystcz/nova-medialibrary-field/commit/7867fa6f0ceb93eb2f059d33f96c250cb1188deb)

I just pasted my `auth.json` to `${{ secrets.COMPOSER_AUTH }}` variable and it works fine. Do you have a Nova 4 licence? I do not think that the actions will run without it. I can provide our unlimited team licence for this purpose, but I don't know wether it goes against the Nova licence or not. :/

We are getting close to mergeable state!

**Comment by dmitrybubyakin** [comment]
Hi @theimerj, I don't have Nova 4 license. I think, tests can be run manually for now.

**Comment by ChristianPavilonis** [comment]
I started using the fork for nova 4. It's working so far.

**Comment by kreejzak** [comment]
So, I went through all the current vue components and made few changes. Mostly just formatted them using prettier to format tailwind classes and removed some inconsistencies such as duplicated classes. Also I've updated tailwindcss to use the latest version. There was no breaking changes so this version bump will only help in future developement imho.

**Comment by theimerj** [comment]
Ok @dmitrybubyakin, if you want, you can merge and publish a new version, which will work with nova 4. @kreejzak went through it, it all seems fine for now. Thank you.

For anyone interested in making progress with this version: There are new ways how Nova 4 handles stuff, so basically if you code dive long enough, you will be able to find ways to improve and do stuff "Nova 4 way". We will open a new PR when we have more time to work on this.

**Comment by dmitrybubyakin** [comment]
Thanks a lot to everyone!

**Comment by dmitrybubyakin** [comment]
v4.0 is published now

**Pull request merged**
