### PR TITLE
Add ability to have big thumbnail on the index 

### PR DESCRIPTION
**Pull request by bomshteyn**
The height and width were hardcoded in the `IndexField.vue` 

I have added a computed property to that component that is set by using `->bigIndexThumbnails()`

**Usage:**
```
// The default width of a thumbnail on index page is set to w-8 h-8.
// The bigThumbnails method makes a singular thumbnail twice  as big as the default (w-16 h-16).
Medialibrary::make('Featured Image', 'featured')
    ->thumbnail('thumbnailConversion')
    ->bigIndexThumbnails(),
```

### CODE REVIEW

**Comment by dmitrybubyakin** [comment]
@bomshteyn checkout new version

**Comment by bomshteyn** [comment]
@dmitrybubyakin Are you saying that this is available in the v2? Can you please explain how?

**Comment by dmitrybubyakin** [comment]
@bomshteyn you can write something like this

```css
.medialibrary-preview-index {
  width: 4rem;
  height: 4rem;
}

.medialibrary-preview-detail {
  width: 12rem;
  height: 12rem;
}
```

https://github.com/dmitrybubyakin/nova-medialibrary-field/commit/90e33d4052aab7a1f7a11e92e46b34ffea9b3aaa

**Comment by bomshteyn** [comment]
@dmitrybubyakin I understand you can do it with CSS it could have been done with the v1 as well even if it didn't have a dedicated class. But IMHO this is a bad design as you would still have `w-8 h-8` in the class list...

Why not allow these classes to be optional / overridable?

**Comment by dmitrybubyakin** [comment]
@bomshteyn You mean like this?
```php
Medialibrary::make(...)->withMeta([
    'indexPreviewClassList' => '...',
    'detailsPreviewClassList' => '...',
])
```

**Comment by bomshteyn** [comment]
Yes, I think this would be great!

**Comment by dmitrybubyakin** [comment]
@bomshteyn I can add this in the current version, but this won't make the field fully configurable. So, you will just be able to change width and height. Changing other css properties will cause some problems.

**Comment by bomshteyn** [comment]
That's fine, that was all my PR was accomplishing as well, just giving an option to have the thumb on the index twice the size.

**Comment by dmitrybubyakin** [comment]
@bomshteyn ok, I'll add this feature

**Comment by bomshteyn** [comment]
thank you!!!

**Comment by dmitrybubyakin** [comment]
@bomshteyn checkout v2.0.2 https://github.com/dmitrybubyakin/nova-medialibrary-field/commit/c011e8bfaeea3de52eaa20e48f31ddc17113e43f

**Pull request closed without merging**
